services:
  router:
    image: ghcr.io/apollographql/router:v2.10.0
    container_name: apollo-router
    ports:
      - 4000:4000
    volumes:
      - ./configs/router/router.yaml:/dist/config/router.yaml
      - ./dist/supergraph.graphql:/dist/config/supergraph.graphql
    environment:
      APOLLO_ROUTER_CONFIG_PATH: /dist/config/router.yaml
      APOLLO_ROUTER_SUPERGRAPH_PATH: /dist/config/supergraph.graphql
      APOLLO_ROUTER_HOT_RELOAD: "true"
      APOLLO_ROUTER_CHECK: "true"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "q1Sh-6xeT1el6Ghiu7VO9A"
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    command: >
      bash -c "
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          echo 'Formatting storage directory...'
          kafka-storage format \
            --ignore-formatted \
            --cluster-id=q1Sh-6xeT1el6Ghiu7VO9A \
            --config /etc/kafka/kafka.properties
        fi
        /etc/confluent/docker/run
      "
    networks:
      - local
        
networks:
  local:
    
